### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by octavio2895** [ClemensElflein/xESC#1]
Hey there! A few weeks ago I saw this ESC on reddit and I thought they were great. I just happen to be searching for a similarly spec'd ESC, but just like you, I found nothing good. I though about making one myself using your design but the STM32 you are using is not easily available anywhere. Do you happen to have any spares laying around? I'm very interested in buying one to test for my projects. How can I reach out to you more privately?

**Comment by ClemensElflein** [comment]
Hi! I'm glad you like the design!
You can contact me via e-mail: clemens dot elflein at gmail dot com

**Comment by ClemensElflein** [comment]
Found your reddit chat, contact info is there!
