### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by ingjae** [ClemensElflein/xESC#14]
Hi, @ClemensElflein  First of all, thank you for this great project.
I am trying to control a small motor, and I think this xESC2 would be just right. 
I want to do a quick test 
So, I contacted you  because I wanted to make a purchase in small quantities.
My mail address is injae.hwang@3watt.co

**Comment by ClemensElflein** [comment]
Hi, sorry that I missed the message. I have redirected this issue to the owner of https://shop.devops.care/ (he produces and sells PCBs for the OpenMower project and therefore also for the xESCs). I personally don't have them in stock.

**Comment by ingjae** [comment]
thank you ! :+1:
