### ISSUE TITLE
xESC2040 - Pull-up to 5V for 3.3V GPIO

### ISSUE THREAD

**Issue by cajt** [ClemensElflein/xESC#5]
The inputs for the Hall-encoder are attached to 5V via pull-up resistors (R8, R9, R12). This will probably cause the ESD protection of the RP2040 to conduct the current to the +3.3V rail. Please add a note if this is intended and okay with the RP2040. 

Suggested solution: With the assumption that he Hall-sensors have open-collector/open-drain outputs, use pull-ups to 3.3V instead of 5V.

**Comment by ClemensElflein** [comment]
Hi @cajt,
thank you so much for the issue! Yes, the STM32 has 5V tolerant IOs and I forgot to adapt that interface. Canceled my PCB order and I'll fix it right away!
